version: '3.6'

services:
  nginx:
    image: nginx:1.17.3-alpine
    volumes:
      - .:/www/polls:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/logs/nginx:/var/log/nginx:rw
    environment:
      - TZ=UTC
    networks:
      - default
    ports:
      - 80:80
    depends_on:
      - php

  php:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    volumes:
      - .:/www/polls:cached
      - ./docker/php/fpm:/etc/php/7.4/fpm:ro
      - ./docker/logs/php:/var/log/php:rw
      - ./storage:/www/polls/storage:rw
    environment:
      - TZ=UTC
    command:
      ./docker/php/boot.sh
    networks:
      - default
    depends_on:
      - postgres

  postgres:
    build:
      context: ./docker/postgres/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=polls
      - POSTGRES_DB=polls
      - TZ=UTC
    networks:
      default:
        aliases:
          - db.local
    ports:
      - 5432:5432

  redis:
    image: redis:5.0.5-alpine
    volumes:
      - ./docker/redis/redis.conf:/etc/redis/redis.conf:ro
      - ./docker/redis/data:/var/lib/redis:rw
      - ./docker/logs/redis:/var/log/redis:rw
    networks:
      default:
        aliases:
          - redis.local
    environment:
      - TZ=UTC

  webpack:
    build:
      context: ./docker/webpack/
      dockerfile: Dockerfile
    volumes:
      - .:/www/polls:cached
    networks:
      - default
    environment:
      - TZ=UTC
    command:
      ./docker/webpack/boot.sh

  swagger:
    image: neemuchaordic/swagger-ui
    networks:
      - default
    volumes:
      - ./docs:/docs
    environment:
      - SWAGGER_JSON=/docs/admin/swagger.yml
    ports:
      - 3000:8080

networks:
  default:
    driver: bridge
