openapi: 3.0.0
servers:
  - url: 'http://dev.polls'
    description: Development
info:
  title: Survey Box
  description: Surveys and polls!
  contact:
    name: Administration
    email: admin@surveybox.com
  license:
    name: proprietary
  version: 1.0.0
paths:
  /admin/survey/getAll:
    get:
      tags:
        - Admin
      description: Returns the list of user's surveys.
      responses:
        '200':
          description: Array of Survey objects.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                      example: 123e4567-e89b-12d3-a456-426655440000
                    title:
                      type: string
                    ownerId:
                      type: string
                      format: uuid
                      example: 123e4567-e89b-12d3-a456-426655440000
                    createdAt:
                      type: string
                      format: date-time
                    updatedAt:
                      type: string
                      format: date-time
  /admin/survey/create:
    get:
      tags:
        - Admin
      description: Returns id of created survey.
      responses:
        '200':
          description: Survey id.
          content:
            application/json:
              schema:
                type: string
                format: uuid
                example: 123e4567-e89b-12d3-a456-426655440000
  /admin/template/getAll:
    get:
      tags:
        - Admin
      description: >-
        Returns the list of available for current user templates. It may be
        system templates like "Blank", "Simple Voting"m, etc... or created by
        user ones.
      responses:
        '200':
          description: Array of Template objects.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                      example: 123e4567-e89b-12d3-a456-426655440000
                    title:
                      type: string
                    ownerId:
                      type: string
                      format: uuid
                      example: 123e4567-e89b-12d3-a456-426655440000
                    public:
                      type: boolean
                    createdAt:
                      type: string
                      format: date-time
                    updatedAt:
                      type: string
                      format: date-time
components: {}
tags: []
